name: Upload Website (Develop)

on:
  push:
    branches:
    - develop

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Git Profile
      run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
  
    - name: Build site
      uses: actions/setup-node@v2
      with:
          node-version: 'v16.6'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_API_TOKEN }}
          default_author: github_actions
    - run: npm install
    - run: echo "" > public/CNAME
    - run: npm run deploy
      env:
        CI: false
