name: Upload Website (Develop)

on:
  push:
    branches:
    - develop

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Git Profile
      run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
  
    - name: Build site
      uses: actions/setup-node@v2
      with:
          node-version: 'v16.6'
          token: ${{ secrets.GITHUB_TOKEN }}
    - run: npm install
    - run: echo "" > public/CNAME
    - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
      env:
        CI: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

