name: Upload Website

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build site
      uses: actions/setup-node@v1
      with:
          node-version: 'v16.6'
    - run: npm install
    - run: npm run deploy
      env:
        CI: false